### ISSUE TITLE
Se queda pegado al redireccionar a página de confirmación 

### ISSUE THREAD

**Issue by carlos-eam** [saulmoralespa/subscription-payu-latam#1]

**Comment by saulmoralespa** [comment]
El overlay se quita cuando  se queda en la página ?

**Comment by saulmoralespa** [comment]
Puedes  compartir la ulr donde lo tienes instalado ?

**Comment by carlos-eam** [comment]
Si, mira aquí está la url, 
https://educabilidad.com/suscripcion
Añade el Plan Bronce que es el que tiene asignado el módulo de PayU

Gracias.

**Comment by carlos-eam** [comment]
En el Holder Name colocar "APPROVED" para que quede aprobada la transacción.

**Comment by saulmoralespa** [comment]
Ya creo  cual sea el problema intente haccer pruebas con las credenciales suministradas por payU latam [ver credenciales](http://developers.payulatam.com/es/sdk/sandbox.html). No desde su cuenta de payU

**Comment by carlos-eam** [comment]
Justo tiene esas credenciales, usé el accountid de México, no he probado con el de Colombia, pero no creo que sea ese el error.

**Comment by carlos-eam** [comment]
Si, tenías razón, acabo de cambiar el accountid por el de Colombia y ya redirige, el problema que no funciona con el México y no sé si en la de producción de México vaya a funcionar. 
Sabes en qué archivo viene configurado el "Country" para modificar y hacerlo funcionar con la cuenta de México. 

Muchas Gracias...

**Comment by saulmoralespa** [comment]
revisa el log  y adjuntalo

**Comment by carlos-eam** [comment]
No arroja nada, sólo pasa lo que ya detectaste en las pruebas con el accountid de México,

Si pongo el accountid de Colombia directamente me manda el siguiente mensaje: Subscription Payu Latam: Check that you have entered correctly merchant id, account id, Api Key, Apilogin. To perform tests use the credentials provided by payU Click here to see Message error: El medio de pago [MASTERCARD] no está soportado code error: 0

Redirige a la pantalla de confirmación de pago pero no procesa el pago ni crea la suscripción.

**Comment by saulmoralespa** [comment]
Acabo de realizar una prueba con las  credenciales de Mexico. Recuerde  quede debe tener correctamente configurada la configuración lea la maldita documentación  en indicaciones correctamente https://wordpress.org/plugins/subscription-payu-latam/
Tanto el país, la moneda deben corresponder al país.

**Comment by saulmoralespa** [comment]
Cierro issue, pruebas realizadas funcionan para México  se debe seguir indicaciones en la documentación. Tanto el país, la moneda deben corresponder al país.

**Comment by saulmoralespa** [comment]
Instale la versión subida en el repositorio de wordpress https://wordpress.org/plugins/subscription-payu-latam/
