### ISSUE TITLE
The payment method value is invalid

### ISSUE THREAD

**Issue by CamiloB** [saulmoralespa/subscription-payu-latam#2]
Hi i go intalled wordpress > 5.0
woocommerce > 3 
And i insttaled subscritions for woocoommerce i read all the documentation but always when i try to use the test i put the credit card that i generate using the link of the documentation but always i have this error
`The payment method value is invalid`

**Comment by saulmoralespa** [comment]
Please update plugin version, download  plugin  from  repository  wordpress https://wordpress.org/plugins/subscription-payu-latam/

**Comment by CamiloB** [comment]
hi i got the last version of the plugin and the error stills on there any suggestion?
