### ISSUE TITLE
Parameter [paymentMethod] is required.

### ISSUE THREAD

**Issue by CamiloB** [saulmoralespa/subscription-payu-latam#3]
i have installed the 2.4.7 woocommerce subcriptions 
woocommerece 3.5.5 
wordpress 5.1
and  Version 1.0.24 subscription-payu-latam

[this is the image of the error](https://ibb.co/0B6wN12)

[this is the product on my web page](https://instagrambot.ninus.co/product/instagram-bot-subscripcion-mensual/)

and i have this error 

`Parameter [paymentMethod] is required.`

can you please help me 

im using the payu credentials for colombia test as you said on the documentation but i got this error
![screencapture-instagrambot-ninus-co-checkout-2019-02-23-19_57_05](https://user-images.githubusercontent.com/6754789/53293694-83fcea80-37a6-11e9-812c-69082ab0b647.png)

**Comment by saulmoralespa** [comment]
You have a problem with the javascript of your installation, you must load the animation of the card

**Comment by CamiloB** [comment]
@saulmoralespa what do you mean whit JavaScript of my install I just download from here and installed like the others plugins, and animation of the card do you mean that when I put the number card must be appear a card logo ?

**Comment by saulmoralespa** [comment]
If you check in the console, of the payment page that does not present error with the javascript
